---
# tasks file for tomcat7
- name: update packages
  apt:
    update_cache: yes
- name: installing tomcat7
  apt:
    name: "{{ tomcat_packag }}"
    state: present 

- name: installing tomcat7
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ tomcat_pack_extra }}"

- name: start tomcat application
  service:
    name: tomcat7
    state: started
  notify: Restarttomcat


- name: Java heap memory increasing
  template:
    src: templates/tomcat7.j2
    dest: /etc/default/tomcat7
  notify: Restarttomcat
 

- name: Configure Tomcat Web Management Interface
  template:
    src: templates/tomcat-users.xml.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: Restarttomcat

